% This program bootstraps a univariate regression with deterministic
% regressors.
% The data are generated by a chosen DGP and then estimated and
% bootstrapped.  The estimated VCV and bootstrapped VCVs are compared for
% three estimators.
clear

J = 1000; %number of Monte Carlos
N = 200; %number of bootstrap iterations
T = 100; %number of observations
K = 8; %number of regressors (less the constant)
A0 = .9;  %transform errors
% Construct Data
beta = [1.1;
1;
0.9;
0.8;
0.7;
0.6;
0.5;
0.4;
0.3];

Sighat_avg = 0;
Sigboot1_avg = 0;
Sigboot2_avg = 0;
for j=1:J
    j
    x = [ones(T,1) random('Normal',0,1,T,K)]; %includes a constant
    eps = random('Normal',0,1,T,1)*A0;
    y = x*beta+eps;

    % ESTIMATE REGRESSION
    %regression 1 coeffs are in column 1, regression 2 are in column 2
    XX = (x'*x)^(-1);
    betahat = XX*x'*y;  
    epshat = y - x*betahat;  %calculate errors
    %construct var-covar matrix
    Sighat = (epshat'*epshat)/(T-(K+1));

    % PERFORM BOOTSTRAP
    % initialize averages of two sigma matrices
    Sigboot1 = 0;
    Sigboot2 = 0;
    for n=1:N
        draw = unidrnd(T,T,1);  %chose random draws with replacement for errors
        epsnew = epshat(draw,:);  %create new error series
        %construct artificial data series
        ynew = x*betahat+epsnew;
        % estimate using OLS
        betatilde = XX*x'*ynew; %calculate and store the estimated betas
        epstilde = ynew - x*betatilde;  %calculate errors
        %construct var-covar matrix
        Sigtilde1 = (epstilde'*epstilde)/(T-(K+1)); %wrong way
        Sigtilde2 = (epstilde'*epstilde)*(T/(T-(K+1))^2); %right way
        Sigboot1 = Sigboot1 + Sigtilde1/N;
        Sigboot2 = Sigboot2 + Sigtilde2/N;    
    end
Sighat_avg = Sighat_avg+Sighat/J;
Sigboot1_avg = Sigboot1_avg+Sigboot1/J;    
Sigboot2_avg = Sigboot2_avg+Sigboot2/J;    
end

% ANALYZE THE BOOTSTRAP RESULTS
disp('"true" value of sigma');
Sigma = A0^2
disp('estimate from original regression');
Sighat_avg
disp('average of "common" estimate over the bootstrap iterations');
Sigboot1_avg
disp('average of "correct" estimate over the bootstrap iterations');
Sigboot2_avg
disp('sigmahatb1 - sigmahat  sigmahatb2 - sigmahat');