% This program bootstraps a bivariate regression with deterministic
% regressors.
% The data are generated by a chosen DGP and then estimated and
% bootstrapped.  The estimated VCV and bootstrapped VCVs are compared for
% three estimators.
clear

J = 1000; %number of Monte Carlos
N = 200; %number of bootstrap iterations
T = 200; %number of observations
K = 16; %number of regressors (less the constant)
A0 = [.9  .1; .1  .9]; %coefficents to transform independent errors into correlated errors
% Construct Data
beta = [1.1 -2.3;
1	-2.2;
0.9	-2;
0.8	-1.8;
0.7	-1.6;
0.6	-1.4;
0.5	-1.2;
0.4	-1;
0.3	-0.8;
0.2	-0.6;
0.1	-0.4;
0	-0.2;
-0.1	0;
-0.2	0.2;
-0.3	0.4;
-0.4	0.6;
-0.5	0.8];

Sighat_avg = zeros(2,2);
Sigboot1_avg = zeros(2,2);
Sigboot2_avg = zeros(2,2);
for j=1:J
    j
    x = [ones(T,1) random('Normal',0,1,T,K)]; %includes a constant
    eps = random('Normal',0,1,T,2)*A0;
    y = x*beta+eps;

    % ESTIMATE REGRESSION
    %regression 1 coeffs are in column 1, regression 2 are in column 2
    XX = (x'*x)^(-1);
    betahat = XX*x'*y;  
    epshat = y - x*betahat;  %calculate errors
    %construct var-covar matrix
    Sighat = (epshat'*epshat)/(T-(K+1));

    % PERFORM BOOTSTRAP
    % initialize averages of two sigma matrices
    Sigboot1 = zeros(2,2);
    Sigboot2 = zeros(2,2);
    for n=1:N
        draw = unidrnd(T,T,1);  %chose random draws with replacement for errors
        epsnew = epshat(draw,:);  %create new error series
        %construct artificial data series
        ynew = x*betahat+epsnew;
        % estimate using OLS
        betatilde = XX*x'*ynew; %calculate and store the estimated betas
        epstilde = ynew - x*betatilde;  %calculate errors
        %construct var-covar matrix
        Sigtilde1 = (epstilde'*epstilde)/(T-(K+1)); %wrong way
        Sigtilde2 = (epstilde'*epstilde)*(T/(T-(K+1))^2); %right way
%         (Sigtilde1 - Sighat)./Sighat
%         (Sigtilde2 - Sighat)./Sighat
%         (Sigtilde1 - Sigtilde2)./Sigtilde2
        Sigboot1 = Sigboot1*(n-1)/n + Sigtilde1/n;
        Sigboot2 = Sigboot2*(n-1)/n + Sigtilde2/n;    
    end
Sighat_avg = Sighat_avg*(j-1)/j+Sighat/j;
Sigboot1_avg = Sigboot1_avg*(j-1)/j+Sigboot1/j;    
Sigboot2_avg = Sigboot2_avg*(j-1)/j+Sigboot2/j;    
end

% ANALYZE THE BOOTSTRAP RESULTS
disp('"true" value of sigma');
Sigma = A0'*A0
disp('estimate from original regression');
Sighat_avg
disp('average of "common" estimate over the bootstrap iterations');
Sigboot1_avg
disp('average of "correct" estimate over the bootstrap iterations');
Sigboot2_avg
% (Sigboot1_avg - Sighat_avg)./Sighat_avg
% (Sigboot2_avg - Sighat_avg)./Sighat_avg
(Sigboot1_avg - Sigboot2_avg)./Sigboot2_avg