function CEE2irf(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-May-2008 19:04:56

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Color',[0 0 0],'Parent',axes1);
set(plot1(1),'LineWidth',2);
set(plot1(3),'LineStyle',':');
set(plot1(4),'LineStyle',':');

